---
# tasks file for apigee-pretask-install-epel
- name: 1. Gather Facts

  set_fact:
    fact_distro_version: '{% if ansible_distribution == CentOS and ansible_distribution_major_version == 7 %}centos_7{% else %}centos_6{% endif %}'

- name: 2. Add repository
  become: true

  yum_repository:
    name: epel
    state: present
    description: EPEL YUM repo
    baseurl: '{% if fact_distro_version == "cento_6"
    %}{{ url_base_v6 }}
    {% elif fact_distro_version == "centos_7"
    %}{{ url_base_v7 }}
    {% endif
    %}'
    notify:
      - update cache
    