---
# tasks file for apigee-pretask-disable-selinux
- name: 1. Install library for SELInux Env
  become: true

  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - libselinux
    - libselinux-utils
    - libselinux-utils
    - selinux-policy-minimum
    - selinux-policy-mls
    - selinux-policy-targeted
    - policycoreutils
    - libselinux-python

- name: 2. Disable SELinux 
  become: true
  
  selinux:
    state: disabled
    