---
# tasks file for apigee-pretask-disable-selinux
#- name: 1. Gather Facts
#  gather_facts: False

#  set_fact:
#    fact_distro_version: "{ {%if ansible_distribution == CentOS and ansible_distribution_major_version == 7|int %}centos_7{% else %}centos_6{% endif %} }"

- name: 2. Install library for SELInux Env
  gather_facts: False
  become: true

  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - libselinux
    - libselinux-utils
    - libselinux-utils
    - selinux-policy-minimum
    - selinux-policy-mls
    - selinux-policy-targeted
    - policycoreutils
    - libselinux-python

- name: 3. Disable SELinux 
  become: true
  
  selinux:
    state: disabled
    