---
# tasks file for apigee-pretask-enable-selinux
#- name: 1. Gather Facts
#  gather_facts: False

#  set_fact:
#    fact_distro_version: "{ {%if ansible_distribution == CentOS and ansible_distribution_major_version == 7|int %}centos_7{% else %}centos_6{% endif %} }"

- name: 2. Install library for SELInux Env
  gather_facts: False
  become: true

- name: 3. Enable SELinux 
  become: true
  
  selinux:
    policy: targeted
    state: enforcing
    