---
# tasks file for apigee-install-edge
- name: 1. Install Packages
  become: true

  vars:
    packages:
    - yum-utils
    - yum-plugin-priorities

  yum:
    name: "{{ packages }}"
    state: present

- name: 2. Package update and Config
  become: true

  yum:
    name: rh-amazon-rhui-client.noarch
    state: latest

- name: 3. Download Script
  become: true

  get_url:
    url: "{{ url_base_script }}"
    dest: "{{ temp_script_path }}"
    mode: 0700

- name: 4. Install Edge
  become: true

  vars:
    aws_region: us-east-2
    commands:
      - '{% if ansible_distribution == "[Cc]entos" %}yum-config-manager --enable ol7_optional_latest{% else %}yum-config-manager --enable rhui-{{ aws_region }} -rhel-server-extras rhui-{{ aws_region }} -rhel-server-optional{% endif %}'
      - "{{ temp_script_path }} apigeeuser={{ apigee_user }} apigeepassword={{ apigee_pass }}"
      - "{{ apigee_bin_path }} apigee-setup install"
  
  raw: "{{ item }}"

  with_items: "{{ commands }}"